apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome-app-deployment
  labels:
    app: welcome-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: welcome-app
  template:
    metadata:
      labels:
        app: welcome-app
    spec:
      containers:
      - name: welcome-app
        image: welcome-app:4cfa23-65
        ports:
        - containerPort: 8080
